{
  "formatVersion": "1.1",
  "component": {
    "group": "org.owasp",
    "module": "dependency-check-gradle",
    "version": "8.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.owasp",
          "module": "dependency-check-core",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-utils",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "net.gpedro.integrations.slack",
          "module": "slack-webhook",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "dependency-check-gradle-8.4.0.jar",
          "url": "dependency-check-gradle-8.4.0.jar",
          "size": 91536,
          "sha512": "a648ee5bb3b3e8ecc4f063c67370ea4955805f6b83703ae746c840ca4215ddb8790ded339f1e82d174711400b8051b9fddaf150d6818f1d98918295b7a85bc83",
          "sha256": "2e27bb3d05bbe71f3415930e19483a0bc88c97f9691e1cb43f2174d351969439",
          "sha1": "c0eb5dde294b73945cbc9d87ecce16511c495014",
          "md5": "3d7ea5c81f9e640f6bbcb26a8ee65038"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.owasp",
          "module": "dependency-check-core",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-utils",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "net.gpedro.integrations.slack",
          "module": "slack-webhook",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "dependency-check-gradle-8.4.0.jar",
          "url": "dependency-check-gradle-8.4.0.jar",
          "size": 91536,
          "sha512": "a648ee5bb3b3e8ecc4f063c67370ea4955805f6b83703ae746c840ca4215ddb8790ded339f1e82d174711400b8051b9fddaf150d6818f1d98918295b7a85bc83",
          "sha256": "2e27bb3d05bbe71f3415930e19483a0bc88c97f9691e1cb43f2174d351969439",
          "sha1": "c0eb5dde294b73945cbc9d87ecce16511c495014",
          "md5": "3d7ea5c81f9e640f6bbcb26a8ee65038"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dependency-check-gradle-8.4.0-javadoc.jar",
          "url": "dependency-check-gradle-8.4.0-javadoc.jar",
          "size": 261,
          "sha512": "642364af0ffbb4054dbf83b063267251a221582f9d138a80b5918e9c5b5ccd1caefed1720e6f21751e4f110255b0c4313f02bfeef4b899f57dc4f0b8e034deda",
          "sha256": "6f5fd957cc9daa867d4bbad689e5deb11094e907c0f9f7a39f89248e00d7f475",
          "sha1": "ec243372c63c6a3bc95f7b4c70b6d824922784f2",
          "md5": "ca7060a29f6493532ec4657aec26959e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dependency-check-gradle-8.4.0-sources.jar",
          "url": "dependency-check-gradle-8.4.0-sources.jar",
          "size": 37117,
          "sha512": "66fa1cd3f3f2450e5a725db9987b4fa9afc7f354a95a7bc60876b6549167256b92044221932851493b280e82999e825b26ff9686a069caebe9e5fea7a0c53deb",
          "sha256": "c0168873e90cc7536f992115fa959d10c092bae81c82548d3e6301887d3299e6",
          "sha1": "c8aab9eac99af42449f7854059cab1d8a010c400",
          "md5": "2c2157db0f1c9069c4fdedd300120a22"
        }
      ]
    }
  ]
}
