pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        // Termux terminal emulator
        maven { url 'https://termux.dev/termux-app/maven/' }
    }
}

rootProject.name = "TabSSH"
include ':app'