name: 💡 Feature Request
description: Suggest a new feature or enhancement for TabSSH
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your idea.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please complete these checks before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been suggested
          required: true
        - label: I have checked the [roadmap](https://github.com/tabssh/android/blob/main/docs/TODO.md) to see if this is planned
          required: true
        - label: I have read the [documentation](https://github.com/tabssh/android/blob/main/README.md)
          required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Currently, TabSSH does not support...
        This makes it difficult to...
        I need this because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Add a button that...
        When the user does X, the app should...
        This would work like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I could manually do X, but...
        Another app solves this by...
        I considered using Y, but...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - SSH Connection & Authentication
        - Terminal Emulator
        - SFTP File Transfer
        - Tab Management
        - Security & Privacy
        - User Interface
        - Settings & Configuration
        - Accessibility
        - Themes & Customization
        - Cloud Sync
        - Keyboard & Input
        - Performance
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my usage)
        - High (significant improvement)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: dropdown
    id: users
    attributes:
      label: Who Would Benefit?
      description: Who would find this feature useful?
      options:
        - All users
        - Power users
        - Accessibility users
        - Developers
        - System administrators
        - Beginners
        - Specific use case (explain in additional context)
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        1. When connecting to multiple servers, I need to...
        2. While transferring large files, it would help to...
        3. For managing SSH keys, I want to...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: |
        If you have mockups, screenshots, or examples from other apps, share them here
      placeholder: Drag and drop images here or paste URLs
    validations:
      required: false

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: |
        Are there any technical details, dependencies, or implementation challenges you're aware of?
      placeholder: |
        This might require...
        Could potentially conflict with...
        Similar to how X app implements...
    validations:
      required: false

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this feature require changes that break existing functionality?
      options:
        - "No (backwards compatible)"
        - "Yes (would break existing functionality)"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, or references about the feature request
      placeholder: |
        - Link to similar features in other apps
        - Related discussion threads
        - Relevant documentation
        - Any other helpful information
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help implement this feature?
      options:
        - label: I would like to work on implementing this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false
