{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-api",
    "version": "2.0.21-1.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-2.0.21-1.0.25.jar",
          "url": "symbol-processing-api-2.0.21-1.0.25.jar",
          "size": 123041,
          "sha512": "3ca66e3eead3ca2a9df00b8a874f3c1c8af53b1fa6f03d56267810fcbb8c6ba8e3eadaee1b3bf11bd6d384f8d682d46d08d2f20aa131fc51b6e7f72fbe001b05",
          "sha256": "17f0b1fe4c99bd8ff350d45076dae4722492b10c95f5f13f24ec133559433407",
          "sha1": "e243d51c9d40bd7775ff883a1212bafb4f2905f8",
          "md5": "7bd30ac5e437fccf31b5cd8d918ff95f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-2.0.21-1.0.25.jar",
          "url": "symbol-processing-api-2.0.21-1.0.25.jar",
          "size": 123041,
          "sha512": "3ca66e3eead3ca2a9df00b8a874f3c1c8af53b1fa6f03d56267810fcbb8c6ba8e3eadaee1b3bf11bd6d384f8d682d46d08d2f20aa131fc51b6e7f72fbe001b05",
          "sha256": "17f0b1fe4c99bd8ff350d45076dae4722492b10c95f5f13f24ec133559433407",
          "sha1": "e243d51c9d40bd7775ff883a1212bafb4f2905f8",
          "md5": "7bd30ac5e437fccf31b5cd8d918ff95f"
        }
      ]
    }
  ]
}
