{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.preference",
    "module": "preference-ktx",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror preference dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          },
          "reason": "Mirror preference dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "preference-ktx-1.2.1.aar",
          "url": "preference-ktx-1.2.1.aar",
          "size": 6284,
          "sha512": "3a60d32c4a27be6172b99c5d80da621567b0a7615b2920746e3966a9cb566d38a1cbba498451a21814ae160c12b89d0a1f3546fefaa457bf464b46fb8b1da4db",
          "sha256": "872a5e3e07c0b8d21cb77769ab2f468b209ab6ec08231874401aecfea304a81c",
          "sha1": "6e9c6ae7537ca0fb93f08ef411530c9809686ba3",
          "md5": "01e94804f66b33cbaa810d60b8cb969a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror preference dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          },
          "reason": "Mirror preference dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "preference-ktx-1.2.1.aar",
          "url": "preference-ktx-1.2.1.aar",
          "size": 6284,
          "sha512": "3a60d32c4a27be6172b99c5d80da621567b0a7615b2920746e3966a9cb566d38a1cbba498451a21814ae160c12b89d0a1f3546fefaa457bf464b46fb8b1da4db",
          "sha256": "872a5e3e07c0b8d21cb77769ab2f468b209ab6ec08231874401aecfea304a81c",
          "sha1": "6e9c6ae7537ca0fb93f08ef411530c9809686ba3",
          "md5": "01e94804f66b33cbaa810d60b8cb969a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "preference-ktx-1.2.1-sources.jar",
          "url": "preference-ktx-1.2.1-sources.jar",
          "size": 1780,
          "sha512": "e4792219a6e1352775bcf39ff8f55beb8d89527e4711be5e63c5525b0d23649280b9c978b15fc8c8ddca7f34e05dae69a668a84458a520ffc35a3074caaf1ad1",
          "sha256": "225d80f9fb06bbd4137a448cdbd094147c9893848e5dbbd959498c2b2b2de700",
          "sha1": "c8df4bdd1cf69b87cbab7120ee314c2c2f6c1bd3",
          "md5": "f2240f2789492e6fc74eed7513ddd436"
        }
      ]
    }
  ]
}
