{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.6.0/kotlinx-serialization-json-1.6.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.6.0.jar",
          "url": "kotlinx-serialization-json-jvm-1.6.0.jar",
          "size": 257194,
          "sha512": "274463ea8d3d94f21b31366711ff614092ace74c347ce083b17ada2ffd16c1dddd47710ba843a36d0518efceb1083f507d2ac1408186cb3994380b63f48a529e",
          "sha256": "1f72bcab9235642591fb5aaba86e1431701ef00effa5f4054d35843dc7951176",
          "sha1": "59761a941bd8691b3ef2447f5b9376868a6b2d7e",
          "md5": "e298505b652f4f79122d910497da8926"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.6.0.jar",
          "url": "kotlinx-serialization-json-jvm-1.6.0.jar",
          "size": 257194,
          "sha512": "274463ea8d3d94f21b31366711ff614092ace74c347ce083b17ada2ffd16c1dddd47710ba843a36d0518efceb1083f507d2ac1408186cb3994380b63f48a529e",
          "sha256": "1f72bcab9235642591fb5aaba86e1431701ef00effa5f4054d35843dc7951176",
          "sha1": "59761a941bd8691b3ef2447f5b9376868a6b2d7e",
          "md5": "e298505b652f4f79122d910497da8926"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.6.0-sources.jar",
          "url": "kotlinx-serialization-json-jvm-1.6.0-sources.jar",
          "size": 80395,
          "sha512": "433f7814a6ba0200eeed0750bba981a72452e2532351a06e468868571bb9ffe3a5ec76a29beddb710b591c1068c60d5e57915301ea8b0a20ebfd4506e039b62d",
          "sha256": "591e9bc8605c0f1fdd9f1358b362e83fb010bcc586e81d30a9aacd9fb3e4ecb0",
          "sha1": "647e4cd4e89aa1dcb89f4ae3afb5c947d8837beb",
          "md5": "dc19ce23c23618b73c1375321c267b9c"
        }
      ]
    }
  ]
}
