{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-blackbird",
    "version": "2.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-blackbird-2.15.2.jar",
          "url": "jackson-module-blackbird-2.15.2.jar",
          "size": 63646,
          "sha512": "b386bae1005b4f31fc8c6942ad714604e03b7d966251f75b540107d1d980d1f3abcc671b5c69ff9085583f7fb7a5ee27997e32b0ffbb04e858764a4e4a04f1eb",
          "sha256": "2e9164023741a2e2b3698025cc467f727a8d9119366cbe5a8b02e821d88d4943",
          "sha1": "1dcd86d03a4cfdf4e2aedf9db38a4f941494d54f",
          "md5": "7a61117824a96c93ff130d33a6258326"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-blackbird-2.15.2.jar",
          "url": "jackson-module-blackbird-2.15.2.jar",
          "size": 63646,
          "sha512": "b386bae1005b4f31fc8c6942ad714604e03b7d966251f75b540107d1d980d1f3abcc671b5c69ff9085583f7fb7a5ee27997e32b0ffbb04e858764a4e4a04f1eb",
          "sha256": "2e9164023741a2e2b3698025cc467f727a8d9119366cbe5a8b02e821d88d4943",
          "sha1": "1dcd86d03a4cfdf4e2aedf9db38a4f941494d54f",
          "md5": "7a61117824a96c93ff130d33a6258326"
        }
      ]
    }
  ]
}
