package io.github.tabssh.ssh.config

import io.github.tabssh.storage.database.entities.ConnectionGroup
import io.github.tabssh.storage.database.entities.ConnectionProfile
import org.json.JSONObject

/**
 * Wave 6.1 — Export `ConnectionProfile` rows to OpenSSH `~/.ssh/config`
 * text format.
 *
 * Symmetric with [SSHConfigParser]: the lines we emit are the same set
 * the parser already understands when reading back. Anything we don't
 * have a clear OpenSSH directive for is silently skipped (we'd rather
 * round-trip-clean than emit junk lines that confuse `ssh`).
 *
 * Group names appear as a leading `# Group: <name>` comment block so the
 * parser's group-detection (`[group]` tag) can re-create them on import,
 * but only when the group reference resolves — orphan groupIds get a
 * plain `Host` block.
 *
 * What we DON'T emit (intentional):
 *  - Passwords or stored secrets (those live in Android Keystore, never
 *    in the config text).
 *  - Telnet protocol toggles (OpenSSH config doesn't model them).
 *  - Per-host color tags / workspace membership / sync metadata.
 */
object SSHConfigExporter {

    private const val HEADER = """# Generated by TabSSH — re-importable via Settings → Import SSH Config.
# Passwords are NEVER written to this file (they live in Android Keystore).
# Hostnames you don't want to leak: redact before sharing.
"""

    fun export(connections: List<ConnectionProfile>, groups: List<ConnectionGroup> = emptyList()): String {
        val groupsById = groups.associateBy { it.id }
        val sb = StringBuilder()
        sb.append(HEADER)
        for (c in connections) {
            sb.append('\n')
            val groupName = c.groupId?.let { groupsById[it]?.name }
            val hostTag = sanitiseHostTag(c.name.ifBlank { c.host })
            val groupSuffix = groupName?.let { "  ## [$it]" }.orEmpty()
            sb.append("Host $hostTag$groupSuffix\n")
            sb.append("    HostName ${c.host}\n")
            if (c.port != 22) sb.append("    Port ${c.port}\n")
            if (c.username.isNotBlank()) sb.append("    User ${c.username}\n")
            if (c.compression) sb.append("    Compression yes\n")
            if (c.connectTimeout != 15) sb.append("    ConnectTimeout ${c.connectTimeout}\n")
            if (c.x11Forwarding) sb.append("    ForwardX11 yes\n")
            if (c.agentForwarding) sb.append("    ForwardAgent yes\n")
            // Identity file: emit only the original path if we kept it in advancedSettings.
            decodeAdvanced(c.advancedSettings).optString("identityFileStr").takeIf { it.isNotBlank() }?.let {
                sb.append("    IdentityFile $it\n")
            }
            // Jump host (subset of profile.proxyType "SSH"): we only know the host:port;
            // user-agnostic ssh config supports "ProxyJump user@host:port".
            if (c.proxyType.equals("SSH", ignoreCase = true) && !c.proxyHost.isNullOrBlank()) {
                val jhUser = c.proxyUsername.takeUnless { it.isNullOrBlank() }
                val jhPort = c.proxyPort?.takeIf { it > 0 && it != 22 }
                val jh = buildString {
                    if (jhUser != null) append("$jhUser@")
                    append(c.proxyHost)
                    if (jhPort != null) append(":$jhPort")
                }
                sb.append("    ProxyJump $jh\n")
            }
            if (!c.envVars.isNullOrBlank()) {
                // Issue #37 — Two related directives:
                //  - `SetEnv NAME=value` if we have a literal value (TabSSH-only;
                //    OpenSSH 7.8+).
                //  - `SendEnv NAME` if the value is empty (TabSSH stores
                //    SendEnv-imported entries as `NAME=`); the value is taken
                //    from the local environment per OpenSSH semantics.
                for (line in c.envVars.lineSequence()) {
                    val t = line.trim()
                    if (t.isEmpty()) continue
                    val eq = t.indexOf('=')
                    when {
                        eq < 0 -> sb.append("    SendEnv $t\n")          // bare name
                        eq == t.length - 1 -> sb.append("    SendEnv ${t.substring(0, eq)}\n")
                        else -> sb.append("    SetEnv $t\n")             // NAME=value
                    }
                }
            }
            // Issue #37 — Round-trip the RemoteCommand directive. Always
            // emitted with `RequestTTY yes` since TabSSH always allocates
            // a PTY when running a RemoteCommand (see SSHConnection.kt).
            if (!c.remoteCommand.isNullOrBlank()) {
                sb.append("    RemoteCommand ${c.remoteCommand}\n")
                sb.append("    RequestTTY yes\n")
            }
        }
        return sb.toString()
    }

    /** Quote / escape Host tags that contain whitespace. */
    private fun sanitiseHostTag(name: String): String {
        val cleaned = name.trim().ifBlank { "host" }
        return if (cleaned.any { it.isWhitespace() }) "\"$cleaned\"" else cleaned
    }

    private fun decodeAdvanced(json: String?): JSONObject = try {
        if (json.isNullOrBlank()) JSONObject() else JSONObject(json)
    } catch (_: Exception) {
        JSONObject()
    }
}
