{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.2"
    }
  },
  "component" : {
    "group" : "com.github.termux",
    "module" : "termux-app",
    "version" : "v0.118.1",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "terminal-emulator-v0.118.1.aar",
      "url" : "terminal-emulator-v0.118.1.aar",
      "size" : 83257,
      "sha512" : "9cb0a0cdba85606f51b8e6544b5e2d2b376d1a63b8213db89de40b8427e3a5bc605f1d1f913e6fb29726f14c881a08955ff2ba1100bacbe24a82a64bd991494d",
      "sha256" : "01694f2ef838e475c36da49104566845b9971cd44552700a04fd80ba2db81561",
      "sha1" : "03bba4c27885660a5bfcc166f0975bbe6a4a8a38",
      "md5" : "47f738ad836fac6db0609ca4fb9d217f"
    } ]
  }, {
    "name" : "releaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "terminal-emulator-v0.118.1.aar",
      "url" : "terminal-emulator-v0.118.1.aar",
      "size" : 83257,
      "sha512" : "9cb0a0cdba85606f51b8e6544b5e2d2b376d1a63b8213db89de40b8427e3a5bc605f1d1f913e6fb29726f14c881a08955ff2ba1100bacbe24a82a64bd991494d",
      "sha256" : "01694f2ef838e475c36da49104566845b9971cd44552700a04fd80ba2db81561",
      "sha1" : "03bba4c27885660a5bfcc166f0975bbe6a4a8a38",
      "md5" : "47f738ad836fac6db0609ca4fb9d217f"
    } ]
  } ]
}